### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by bethesque** [Dashrath18/openshift-pact-broker#1]
This is cool. Can I suggest you call it kubernetes-pact-broker or openshift-pact-broker so that people will find it more easily? Also, I'd recommend using pactfoundation/pact-broker, as it's much smaller, and more suited for use in docker managed environments.

Also, have you seen this? https://github.com/pact-foundation/pact-broker-docker#running-with-openshift

**Comment by DashrathMundkar** [comment]
Thank you for the feedback. I will do the changes. Also you can share my GitHub repo into your main repository just for example.

**Comment by DashrathMundkar** [comment]
Hi @bethesque,

The https://github.com/jaimeniswonger/pact-broker-openshift repository is not working anymore and this repository has wrong port where pact broker exposes. I had problem with this that's why I have developed my own config files for Openshift and Kubernetes. It would be good if you update this my repo to your main pact foundation repository so that many people would be grateful.

Thanks,
Dashrath
